Added route checking and major switcher tidy-up

diff --git a/wiperf_switcher b/wiperf_switcher
--- a/wiperf_switcher
+++ b/wiperf_switcher
@@ -7,6 +7,8 @@
 # History:
 #
 # v0.01 - 8th Dec 2019 - Initial version
+# v0.02 - 11th Dec 2019 - Fixed awk for multiple spaces, command ordrering, ufw rules 
+# v0.03 - 14th Dec 2019 - Lots of updates for eth0 static routes, wlan0 check etc.
 
 set -e
 
@@ -15,9 +17,12 @@ DESC="Script to switch wiperf on/off"
 VERSION=0.01
 STATUS_FILE="/home/wlanpi/wiperf/wiperf.on"
 CFG_FILE="/home/wlanpi/wiperf/config.ini"
+LOG_FILE="/home/wlanpi/wiperf/switcher.log"
 
+# Check we're root
 if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root" 
+   err_msg="This script must be run as root" 
+   echo $err_msg | tee $LOG_FILE
    exit 1
 fi
 
@@ -25,19 +30,112 @@ fi
 #
 # Activate wiperf:
 #
-# 1. Backup various existing files to allow restoration when wiperf
-#    deactivated
-# 2. Remove a number of existing files that need to be replaced
-# 3. Create links from deleted file locations to wiperf config files
-# 4. Create status file to indicate wiperf is active
-# 5. Reboot the wlanpi to ensure clean activation
+# 1.  Check wlan0 is available (wireless NIC plugged in)
+# 2.  Read in test interval & offset from config file
+# 3.  Check if our mgt interface is defined in config.ini
+# 4.  Check Splunk server IP set
+# 5.  Check whether we use eth0 at mgt interface (static route req if we are)
+# 6.  if we're using eth0 as mgt i/f:
+#         a. Check eth0 is up
+#         b. Figure out gateway used by eth0
+#         c. Write route to /etc/network/interfaces 
+# 7.  Add fw rules to harden eth0 & wlan0
+# 8.  Add crontab entry to perform 5 min polling
+# 9.  Backup various existing files to allow restoration when wiperf
+#     deactivated
+# 10.  Remove a number of existing files that need to be replaced
+# 11. Create links from deleted file locations to wiperf config files
+# 12. Create status file to indicate wiperf is active
+# 13. Reboot the wlanpi to ensure clean activation
 #
-# Note: /etc/sysctl.conf only included to ensure forwarding
-#       cannot be accidentally be enabled in probe mode
+# Note: /etc/sysctl.conf included to ensure forwarding
+#    cannot be accidentally be enabled in probe mode if
+#    has been changed by some other process
 #
 ###############################################################################
 wiperf_on () {
-  echo "Enabling wiperf..."
+  #echo "Enabling wiperf..."
+
+  # Check if wlan0 available before we start changing things 
+  WLAN_IF=`ip a | grep wlan0` || true
+  if  [ -z "$WLAN_IF" ]; then
+    echo "No WLAN Interface" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # get test interval
+  TEST_INTERVAL=`cat /home/wlanpi/wiperf/config.ini | grep test_interval | awk -F'[:][[:space:]]*' '{print $2}'` || true
+  if  [ -z "TEST_INTERVAL" ]; then
+    echo "No test interval in config" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # get test offset value
+  TEST_OFFSET=`cat /home/wlanpi/wiperf/config.ini | grep test_offset | awk -F'[:][[:space:]]*' '{print $2}'` || true
+  if  [ -z "TEST_OFFSET" ]; then
+    echo "No test offset in config" | tee $LOG_FILE 
+    exit 0
+  fi
+
+
+  # figure out the interface we send mgt traffic over
+  MGT_IF=`cat /home/wlanpi/wiperf/config.ini | grep mgt_if | awk -F'[:][[:space:]]*' '{print $2}'` || true
+  # check if we have a mgt interface
+  if [ -z "$MGT_IF" ]; then
+    echo "No mgt interface config" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # figure out the Splunk IP
+  SPLUNK_IP=`cat /home/wlanpi/wiperf/config.ini | grep data_host | awk -F'[:][[:space:]]*' '{print $2}'` || true
+  echo $SPLUNK_IP
+  # check if we have a Splunk IP
+  if [ -z "$SPLUNK_IP" ]; then
+    echo "No Splunk IP config" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # If we're using Splunk via eth0, set up static route
+  if [ "$MGT_IF" == "eth0" ]; then
+    # Using eth0 - need to set static route back to Splunk if eth0 up
+
+    # is eth0 up...fail if not
+    ETH_STATUS=`ip a | grep eth0 | grep 'state UP'` || true
+    if  [ -z "$ETH_STATUS" ]; then
+      echo "eth0 is down..." | tee $LOG_FILE 
+      exit 0
+    fi
+
+    # get def gw of eth0
+    ETH_DEF_ROUTE=`ip route | grep eth0 | grep default | awk '{print $3}'` || true
+    # check if we got gateway OK
+    if [ -z "$ETH_DEF_ROUTE" ]; then
+      echo "Eth0 cannot get def gw" | tee $LOG_FILE 
+      exit 0
+    fi  
+
+    # add static route to end of interfaces file
+    STATIC_CMD="post-up ip route add $SPLUNK_IP via $ETH_DEF_ROUTE dev eth0 "
+    echo -e "\n" >> /home/wlanpi/wiperf/conf/etc/network/interfaces
+    echo $STATIC_CMD >> /home/wlanpi/wiperf/conf/etc/network/interfaces
+
+  fi
+
+  # Add crontab entry
+  line="${TEST_OFFSET}-59/${TEST_INTERVAL} * * * * /usr/bin/python3 /home/wlanpi/wiperf/wi-perf.py > /home/wlanpi/wiperf/wiperf.log 2>&1"
+  (crontab -u wlanpi -l; echo "$line" ) | crontab -u wlanpi -
+  LAST_RESULT=$?
+  if [ $LAST_RESULT -ne 0 ]; then
+    echo "Cron add failed" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # Harden eth0 & wlan0 by adding fw rules - allow only ssh in on eth0 & wlan0
+  ufw insert 1 allow in on eth0 to any port ssh
+  ufw insert 2 deny in on eth0
+  ufw insert 3 allow in on wlan0 to any port ssh
+  ufw insert 4 deny in on wlan0
+
   #Backup existing config files
   cp /etc/network/interfaces /etc/network/interfaces.probe
   cp /etc/sysctl.conf /etc/sysctl.conf.probe
@@ -53,32 +151,6 @@ wiperf_on () {
   ln -s /home/wlanpi/wiperf/conf/etc/sysctl.conf /etc/sysctl.conf
   ln -s /home/wlanpi/wiperf/conf/etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
 
-  # If we're using Splunk via eth0, set up static route
-  MGT_IF=`cat /home/wlanpi/wiperf/config.ini | grep mgt_if | awk '{print $2}'`
-
-  if [ "$MGT_IF" == "eth0" ]; then
-    # Using eth0 - need to set static route back to Splunk
-    ETH_DEF_ROUTE=`ip route | grep eth0 | grep default | awk '{print $3}'`
-    SPLUNK_IP=`cat /home/wlanpi/wiperf/config.ini | grep data_host | awk '{print $2}'`
-
-    # add static route to interfaces file
-    STATIC_CMD="post-up ip route add $SPLUNK_IP via $ETH_DEF_ROUTE dev eth0 "
-    echo $STATIC_CMD >> /home/wlanpi/wiperf/conf/etc/network/interfaces
-
-  fi
-
-  # Harden eth0 by adding fw rules
-  SPLUNK_IP=`cat /home/wlanpi/wiperf/config.ini | grep data_host | awk '{print $2}'`
-
-  ufw insert 1 allow in on eth0 from $SPLUNK_IP
-  ufw insert 2 allow out on eth0 to $SPLUNK_IP
-  ufw insert 3 deny in on eth0
-  ufw insert 4 deny out on eth0
-
-  # Add crontab entry
-  line="*/5 * * * * /usr/bin/python3 /home/wlanpi/wiperf/wi-perf.py > /home/wlanpi/wiperf/wiperf.log 2>&1"
- (crontab -u wlanpi -l; echo "$line" ) | crontab -u wlanpi -
-
   touch $STATUS_FILE
 
   echo "WLANPi will now reboot"
@@ -90,17 +162,47 @@ wiperf_on () {
 #
 # Deactivate wiperf:
 #
-# 1. Remove links created during activation
-# 2. Restore config files backed up during activation
-# 3. Remove firewall rules added during activation
-# 4. Remove status file to indicate wiperf no longer active
-# 5. Reboot wlanpi to provide clean restoration of services
+# 1. remove crontab entry to stop polling
+# 2. Remove eth0 static route (if needed)
+# 3. Remove fw rules added during mode switch
+# 5. Remove links created during activation
+# 6. Restore config files backed up during activation
+# 7. Remove status file to indicate wiperf no longer active
+# 8. Reboot wlanpi to provide clean restoration of services
 #
 ###############################################################################
 wiperf_off () {
-  echo "Disabling wiperf..."
-  # Remove links to config files
+  #echo "Disabling wiperf..."
 
+  # Remove crontab entry
+  crontab -u wlanpi -l | grep -v 'wi-perf.py'  | crontab -u wlanpi -
+  LAST_RESULT=$?
+  if [ $LAST_RESULT -ne 0 ]; then
+    echo "Cron remove failed" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  # figure out the interface we send mgt traffic over
+  MGT_IF=`cat /home/wlanpi/wiperf/config.ini | grep mgt_if | awk -F'[:][[:space:]]*' '{print $2}'` || 
+  # check if we have a mgt interface
+  if [ -z "$MGT_IF" ]; then
+    echo "No mgt interface in config file" | tee $LOG_FILE 
+    exit 0
+  fi
+
+  if [ "$MGT_IF" == "eth0" ]; then
+    # Using eth0 - need to remove static route back to Splunk
+    sed -i '$ d' /home/wlanpi/wiperf/conf/etc/network/interfaces
+  fi
+
+  # Remove eth0 & wlan0 fw rules
+  # Harden eth0 & wlan0 by adding fw rules - allow only ssh in on eth0 & wlan0
+  ufw delete allow in on eth0 to any port ssh
+  ufw delete deny in on eth0
+  ufw delete allow in on wlan0 to any port ssh
+  ufw delete deny in on wlan0
+
+  # Remove links to config files
   unlink /etc/network/interfaces
   unlink /etc/sysctl.conf
   unlink /etc/wpa_supplicant/wpa_supplicant.conf
@@ -110,29 +212,10 @@ wiperf_off () {
   cp /etc/sysctl.conf.probe /etc/sysctl.conf
   cp /etc/wpa_supplicant/wpa_supplicant.conf.probe /etc/wpa_supplicant/wpa_supplicant.conf
 
-# If we're using Splunk via eth0, remove static route
-  MGT_IF=`cat /home/wlanpi/wiperf/config.ini | grep mgt_if | awk '{print $2}'`
-
-  if [ "$MGT_IF" == "eth0" ]; then
-    # Using eth0 - need to remove static route back to Splunk
-    sed -i '$ d' /home/wlanpi/wiperf/conf/etc/network/interfaces
-  fi
-
-  # Remove eth0 fw rules
-  SPLUNK_IP=`cat /home/wlanpi/wiperf/config.ini | grep data_host | awk '{print $2}'`
-
-  ufw delete allow in on eth0 from $SPLUNK_IP
-  ufw delete allow out on eth0 to $SPLUNK_IP
-  ufw delete deny in on eth0
-  ufw delete deny out on eth0
-
   echo "WLANPi will now reboot"
   if [ -e "$STATUS_FILE" ]; then
     rm $STATUS_FILE
   fi
-
-  # Remove crontab entry
- crontab -u wlanpi -l | grep -v 'wi-perf.py'  | crontab -u wlanpi -
 
   sleep 1
   reboot
